### ISSUE TITLE
CKANCON 2015: CKAN Technical working group schedule

### ISSUE THREAD

**Issue by wardi** [ckan/ideas-and-roadmap#146]
This is a ticket to discuss the [CKAN developer working group schedule](http://www.eventbrite.com/e/ckancon-2015-tickets-16681567016). In the afternoon at CKANCon the Government working group will be doing their thing while we have 2.5 hours to discuss whatever we like. This session will be available to remote participants as well.

I hope we can use the time to have some good arguments, find ways to align on similar features, talk about future core development and learn more about some of the great ckan extensions being built. Please help by suggesting additional topics to discuss and volunteer to join the discussion on any of the topics already suggested by adding comments below.

This list has moved to https://pad.okfn.org/p/ckancon where everyone can edit it.

**Comment by danmihaila** [comment]
Hello, i am interested into "Visualizations and res views" and "core CKAN" topics.

**Comment by jqnatividad** [comment]
Hi! Interested to join in on ETL discussions.

Also would be interesting to discuss:

* PostgreSQL 9.4 and JSONB (#117 and #143)
* Federated Search (and actually federating search across agency CKAN instances rather than just on harvested data for the regional portal usecase)
* Quantifying open data usage beyond Google Analytics and roadmap for built-in stats (e.g. API usage, number of embeds,  auto-showcase of downstream data consumers, popular datasets, etc.)
* What can be done to incentivize dog-fooding (e.g. geocoder integration, data enrichment integration, revisions, API mgmt best practices (apigee, 3scale, mashery, etc.) )
* creative ways to accelerate/fund high-priority ideas-and-roadmap issues

**Comment by wardi** [comment]
@jqnatividad  Awesome! added.

**Comment by wardi** [comment]
I've moved the topic list to https://pad.okfn.org/p/ckancon where everyone can edit it.

**Comment by jqnatividad** [comment]
Closing now that CKANCon 2015 is over.  See you at CKANCon 2016 in Madrid! ;)
